version: "3"

services:
  node:
    build:
      context: .
      target: DEV
    container_name: node
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - rede

networks:
  rede:
    driver: bridge
